### ISSUE TITLE
Clojars

### ISSUE THREAD

**Issue by misuba** [tatut/ripley#10]
Would it be possible/advisable to get this library a little easier to use by getting it onto Clojars?

**Comment by tatut** [comment]
Possible, I haven't needed it myself so haven't gotten around to it.

For now you can use lein-git-down plugin to use from leiningen projects.

**Comment by misuba** [comment]
It looks like Leiningen needs a bare-minimum project.clj to deal with a dependency, even via git. I can do one up for you and send a PR if you like.

**Comment by tatut** [comment]
You don't need a project.clj if you use lein-git-down plugin in leiningen.

I have used xtdb-inspector (that depends on ripley) from a leiningen project.

You could try something like this:
```
(defproject foo ...
  :dependencies [[ripley "commit sha here"]]
  :git-down {ripley {:coordinates tatut/ripley}}
  :plugins [[reifyhealth/lein-git-down "0.4.0"]])
```

**Comment by misuba** [comment]
Ah, I read lein-git-deps instead of lein-git-down! My bad

**Comment by misuba** [comment]
```
Could not find artifact ripley:ripley:jar:bca327a in central (https://repo1.maven.org/maven2/)
Could not find artifact ripley:ripley:jar:bca327a in clojars (https://repo.clojars.org/)
```

(Most likely I'm just dumb and can't figure out how to get github to tell me the full sha)

(EDIT nope, same error after I found it)

(EDIT EDIT my fork with a project.clj also doesn't seem to fix this. The fork does work with lein-git-deps. Huh. `¯\_(ツ)_/¯`)
