### ISSUE TITLE
Use sci for interactivity?

### ISSUE THREAD

**Issue by den1k** [tatut/ripley#4]
IMO the major challenges of client-side event handling in server side apps are:

1. Deciding the frequency at which to send an event. For example, should "mousemove" be sent every time or throttled? This varies from case to case.
2. Serializing the event. Which data does the server care about? This varies from case to case.
3. e.preventDefault / e.stopPropagation – this needs to happen immediately and client-side since the JS runtime will move into the next frame. Sometimes this requires client-side logic, e.g. did the user `click-outside?` an element

So what if ripley used [sci](https://github.com/borkdude/sci) for event-handling functions? This would allow to make client-side decisions in Clojure. The functions would be wrapped by a macro like `ripley.html/html` to send additional EDN or additional code to eval server-side.

Inspiration: [bb-web](https://github.com/kloimhardt/bb-web#bb-web) which uses sci as its runtime for a CLJS app. [demo](https://kloimhardt.github.io/guestbook_0.html)

**Comment by den1k** [comment]
cc @borkdude

**Comment by den1k** [comment]
Here's some pseudo-code of what this could look like:

```clojure
[:div
 {:data-live-id "0"
  :on-click (env
              :client (fn [ev]
                        (.preventDefault ev)
                        {:target-node-id (.. ev -target (getAttribute "data-live-id"))})
              :server (fn [{:keys [target-node-id]}]
                        ;; can trigger reactive update from server
                        (assoc state :active-node target-node-id)))}
 [:span {:data-live-id "1"} "child 1"]
 [:span {:data-live-id "2"} "child 2"]]
```

the client portion would be wrapped by sci, like
```js
(e) => {
  const handler = sci.eval_string(`(fn [ev]
                   (.preventDefault ev)
                   {:target-node-id (.. ev -target (getAttribute " data-live-id "))})`)
  const ret = handler(e)
  // ctx contains information to invoke the right function on the server
  ret && sendToServer(ctx, ret)
}
```

**Comment by tatut** [comment]
Sure, I don't see why you couldn't include sci in your page and use sci eval. 
It doesn't look like ripley would need specific support for that. The compiled SCI looks pretty big so I wouldn't include it by default.

**Comment by den1k** [comment]
Nice, can I add js event-handlers or would they get overwritten/wrapped by the `html` macro?
Re: SCI's source being large, it can just be loaded after the initial render. It's unlikely the user will have time to interact with the page until then.

**Comment by tatut** [comment]
So you would basically need a function/macro that registers the callback and then generates js string to call sci.

`register-callback!` returns the callback id which you would hook into the code running in js side and invoke with `ripley.send`.


The function/macro should just return a JS-string and it will be output as is.

**Comment by tatut** [comment]
Closing this. SCI can be used as an auxiliary library, doesn't need Ripley support.
